### ISSUE TITLE
Crash when selecting a view

### ISSUE THREAD

**Issue by edorrington** [TablePlus/TablePlus-Linux#125]
1. Database version (Ex: PostgreSQL 10.0): MySQL 5.7.35, MySQL 5.6.12

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): build 118

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 20.04

4. The steps to reproduce this issue: Click on any view in the table list

TablePlus crashes with a segmentation violation when clicking on any view in a MySQL database. I've tested it on several different databases, on several servers, and gotten the same results. Clicking on a view in Postgres or SQLite is fine, it's only MySQL that is causing the issue.

**Comment by huyphams** [comment]
Hi @edorrington I could not reproduce the issue, however I just pushed the build 120 with a bugfixes that is related to view view structure, could you please try it and see how it goes?

**Comment by huyphams** [comment]
Please let me know if you are still seeng the issue. Thanks

**Comment by edorrington** [comment]
Thanks for the quick response. Sorry I wasn't able to test until now, but after upgrading to build 120, the problem is still occurring. If it's helpful, the segmentation violation is happening within `strtol`, which is being called by `table_plus_drivers_my_sql_driver_real_count_rows` (in MySQLDriver.vala line 316).

**Comment by huyphams** [comment]
Oh thanks, it could because the database return invalid integer format. I've handled it. Please update the app to the build 126 and see how it goes.
Thanks again @edorrington

**Comment by edorrington** [comment]
Great, thanks! That fixed it. I really appreciate the quick response. And thanks for creating TablePlus; I use it every day, on both Mac and Linux, and it's a critical part of my work.
