### ISSUE TITLE
Error Connecting to Cassandra

### ISSUE THREAD

**Issue by hozt** [TablePlus/TablePlus-Linux#67]
Build 54
Ubuntu 20.04
Cassandra 3.11.6

Trying to connect to a local cassandra database.  No ssl enabled.

The following error and warning repeats several times:

`1592528567.644 [ERROR] (cluster_connector.cpp:192:void datastax::internal::core::ClusterConnector::on_connect(datastax::internal::core::ControlConnector*)): Unable to establish a control connection to host 127.0.0.1 because of the following error: Underlying connection error: Received error response 'Invalid or unsupported protocol version (66); supported versions are (3/v3, 4/v4, 5/v5-beta)' (0x0200000A)`

`
1592528567.644 [WARN] (cluster_connector.cpp:289:void datastax::internal::core::ClusterConnector::on_connect(datastax::internal::core::ControlConnector*)): Host 127.0.0.1 does not support protocol version DSEv2. Trying protocol version DSEv1...
1592528567.644 [ERROR] (cluster_connector.cpp:192:void datastax`

**Comment by mjahmadi** [comment]
same problem here :(

**Comment by iChaos26** [comment]
Same here guys:
 ```Underlying connection error: Received error response 'Invalid or unsupported protocol version (66); supported versions are (3/v3, 4/v4, 5/v5-beta)' (0x0200000A)```

**Comment by caio-farias** [comment]
Ubuntu 20.04.2 LTS  -- 64-bit
cqlsh 5.0.1; Cassandra 3.11.10; CQL spec 3.4.4; Native protocol v4

Same here!!

**Comment by huyphams** [comment]
Hi @hozt @iChaos26 @mjahmadi @caio-farias please upgrade to the build 140, it should fix this issue.

**Comment by GomathinayagamManakavalan-Rogers** [comment]
using version Version 5.8.4 (532). Still showing the same error. "Underlying connection error: Connection timeout"
